source :rubygems

gem 'rack', '1.4.1'
gem "sinatra", :require => "sinatra/base"
gem "sinatra-contrib"
gem "sinatra-session"
gem 'nokogiri'
gem 'mechanize', "2.3"
gem 'json'
gem 'typhoeus'
gem 'sqlite3-ruby', '1.2.5', :require => 'sqlite3'
